2.4.101 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.101-debian"
    VERSION: "2.4.101"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-12
  only:
    changes:
      - 2.4.101-debian/*
  except:
    refs:
      - schedules
 
2.4.101 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.101-debian"
    VERSION: "2.4.101"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-12
  only:
    refs:
      - schedules 

2.4.101 Manual:
  extends: .build
  variables:
    VERSION: "2.4.101"
    FOLDER: "2.4.101-debian"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-12
  when: manual
  except:
    refs:
      - schedules