build 2.4.nightly-ubuntu:
  extends: .build
  variables:
    VERSION: "2.4.nightly-ubuntu"

test 2.4.nightly-ubuntu:
  extends: .test
  variables:
    VERSION: "2.4.nightly-ubuntu"
  only:
    changes:
    - 2.4.nightly-ubuntu/*
    