build 2.4.102-debian:
  extends: .build
  variables:
    FOLDER: "2.4.102-debian"
    VERSION: "2.4.102"
    TAGS: "${FOLDER}-dev"
    RELEASE_DATE: 2018-12


test 2.4.102-debian:
  extends: .test
  variables:
    VERSION: "2.4.102-debian"
  only:
    changes:
    - 2.4.102-debian/*
    