2.4.109 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.109-debian"
    VERSION: "2.4.109"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-08
  only:
    changes:
      - 2.4.109-debian/*
  except:
    refs:
      - schedules
 
2.4.109 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.109-debian"
    VERSION: "2.4.109"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-08
  only:
    refs:
      - schedules 

2.4.109 Manual:
  extends: .build
  variables:
    VERSION: "2.4.109"
    FOLDER: "2.4.109-debian"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-08
  when: manual
  except:
    refs:
      - schedules