build 2.4.97-debian:
  extends: .build
  variables:
    VERSION: "2.4.97-debian"

test 2.4.97-debian:
  extends: .test
  variables:
    VERSION: "2.4.97-debian"
  only:
    changes:
    - 2.4.97-debian/*