2.4.94 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.94-ubuntu"
    VERSION: "2.4.94"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-09
  only:
    changes:
      - 2.4.94-ubuntu/*
  except:
    refs:
      - schedules
 
2.4.94 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.94-ubuntu"
    VERSION: "2.4.94"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-09
  only:
    refs:
      - schedules 

2.4.94 Manual:
  extends: .build
  variables:
    VERSION: "2.4.94"
    FOLDER: "2.4.94-ubuntu"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-09
  when: manual
  except:
    refs:
      - schedules