2.4.92 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.92-ubuntu"
    VERSION: "2.4.92"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    changes:
      - 2.4.92-ubuntu/*
  except:
    refs:
      - schedules
 
2.4.92 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.92-ubuntu"
    VERSION: "2.4.92"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    refs:
      - schedules 

2.4.92 Manual:
  extends: .build
  variables:
    VERSION: "2.4.92"
    FOLDER: "2.4.92-ubuntu"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  when: manual
  except:
    refs:
      - schedules