#!/bin/bash
set -x
source ./configuration.sh

# Default Build Args
BUILD_ARGS+="
    --build-arg RELEASE_DATE="$(date +"%Y-%m-%d")" \
    --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --build-arg NAME="$CONTAINER_NAME" \
    --build-arg GIT_REPO="$GIT_REPO_URL" \
    --build-arg VCS_REF=$(git rev-parse --short HEAD) \
    --build-arg VERSION="$VERSION" \
"

sudo docker build \
        $BUILD_ARGS \
    -f $DOCKERFILE_PATH -t $IMAGE_NAME .

docker push $IMAGE_NAME