2.4.99 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.99-debian"
    VERSION: "2.4.99"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-12
  only:
    changes:
      - 2.4.99-debian/*
  except:
    refs:
      - schedules
 
2.4.99 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.99-debian"
    VERSION: "2.4.99"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-12
  only:
    refs:
      - schedules 

2.4.99 Manual:
  extends: .build
  variables:
    VERSION: "2.4.99"
    FOLDER: "2.4.99-debian"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-12
  when: manual
  except:
    refs:
      - schedules