
build 2.4.99-debian:
  extends: .build
  variables:
    FOLDER: "2.4.99-debian"
    VERSION: "2.4.99"
    TAGS: "${FOLDER}-dev"
    RELEASE_DATE: 2018-12

test 2.4.99-debian:
  extends: .test
  variables:
    FOLDER: "2.4.99-debian"
    VERSION: "2.4.99"
    TAGS: "${FOLDER}-dev"
    RELEASE_DATE: 2018-12
  only:
    changes:
    - 2.4.99-debian/*
    