2.4.91 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.91-ubuntu"
    VERSION: "2.4.91"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    changes:
      - 2.4.91-ubuntu/*
  except:
    refs:
      - schedules
 
2.4.91 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.91-ubuntu"
    VERSION: "2.4.91"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    refs:
      - schedules 

2.4.91 Manual:
  extends: .build
  variables:
    VERSION: "2.4.91"
    FOLDER: "2.4.91-ubuntu"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  when: manual
  except:
    refs:
      - schedules