2.4.89 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.89-ubuntu"
    VERSION: "2.4.89"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    changes:
      - 2.4.89-ubuntu/*
  except:
    refs:
      - schedules
 
2.4.89 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.89-ubuntu"
    VERSION: "2.4.89"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    refs:
      - schedules 

2.4.89 Manual:
  extends: .build
  variables:
    VERSION: "2.4.89"
    FOLDER: "2.4.89-ubuntu"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  when: manual
  except:
    refs:
      - schedules