2.4.90 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.90-ubuntu"
    VERSION: "2.4.90"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    changes:
      - 2.4.90-ubuntu/*
  except:
    refs:
      - schedules
 
2.4.90 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.90-ubuntu"
    VERSION: "2.4.90"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    refs:
      - schedules 

2.4.90 Manual:
  extends: .build
  variables:
    VERSION: "2.4.90"
    FOLDER: "2.4.90-ubuntu"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  when: manual
  except:
    refs:
      - schedules