2.4.100 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.100-debian"
    VERSION: "2.4.100"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-12
  only:
    changes:
      - 2.4.100-debian/*
  except:
    refs:
      - schedules
 
2.4.100 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.100-debian"
    VERSION: "2.4.100"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-12
  only:
    refs:
      - schedules 

2.4.100 Manual:
  extends: .build
  variables:
    VERSION: "2.4.100"
    FOLDER: "2.4.100-debian"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-12
  when: manual
  except:
    refs:
      - schedules