build 2.4.100-debian:
  extends: .build
  variables:
    VERSION: "2.4.100-debian"


test 2.4.100-debian:
  extends: .test
  variables:
    VERSION: "2.4.100-debian"
  only:
    changes:
    - 2.4.100-debian/*
    