2.4.88 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.88-ubuntu"
    VERSION: "2.4.88"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    changes:
      - 2.4.88-ubuntu/*
  except:
    refs:
      - schedules
 
2.4.88 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.88-ubuntu"
    VERSION: "2.4.88"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  only:
    refs:
      - schedules 

2.4.88 Manual:
  extends: .build
  variables:
    VERSION: "2.4.88"
    FOLDER: "2.4.88-ubuntu"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-06
  when: manual
  except:
    refs:
      - schedules