2.4.105 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.105-debian"
    VERSION: "2.4.105"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-08
  only:
    changes:
      - 2.4.105-debian/*
  except:
    refs:
      - schedules
 
2.4.105 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.105-debian"
    VERSION: "2.4.105"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-08
  only:
    refs:
      - schedules 

2.4.105 Manual:
  extends: .build
  variables:
    VERSION: "2.4.105"
    FOLDER: "2.4.105-debian"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-08
  when: manual
  except:
    refs:
      - schedules