2.4.96 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.96-ubuntu"
    VERSION: "2.4.96"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-11
  only:
    changes:
      - 2.4.96-ubuntu/*
  except:
    refs:
      - schedules
 
2.4.96 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.96-ubuntu"
    VERSION: "2.4.96"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-11
  only:
    refs:
      - schedules 

2.4.96 Manual:
  extends: .build
  variables:
    VERSION: "2.4.96"
    FOLDER: "2.4.96-ubuntu"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-11
  when: manual
  except:
    refs:
      - schedules