2.4.95 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.95-ubuntu"
    VERSION: "2.4.95"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-09
  only:
    changes:
      - 2.4.95-ubuntu/*
  except:
    refs:
      - schedules
 
2.4.95 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.95-ubuntu"
    VERSION: "2.4.95"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-09
  only:
    refs:
      - schedules 

2.4.95 Manual:
  extends: .build
  variables:
    VERSION: "2.4.95"
    FOLDER: "2.4.95-ubuntu"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2018-09
  when: manual
  except:
    refs:
      - schedules