build 2.4.98-debian:
  extends: .build
  variables:
    VERSION: "2.4.98-debian"
    TAGS: "${VERSION}-dev"
    RELEASE_DATE: 2018-11

test 2.4.98-debian:
  extends: .test
  variables:
    VERSION: "2.4.98-debian"
  only:
    changes:
    - 2.4.98-debian/*