2.4.nightly Changes:
  extends: .build
  variables:
    FOLDER: "2.4.nightly-debian"
    VERSION: "2.4.nightly"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-06
  only:
    changes:
      - 2.4.nightly-debian/*
 
2.4.nightly Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.nightly-debian"
    VERSION: "2.4.nightly"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-06
  only:
    refs:
      - schedules 

2.4.nightly Manual:
  extends: .build
  variables:
    VERSION: "2.4.nightly"
    FOLDER: "2.4.nightly-debian"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-06
  when: manual
  