2.4.107 Changes:
  extends: .build
  variables:
    FOLDER: "2.4.107-debian"
    VERSION: "2.4.107"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-08
  only:
    changes:
      - 2.4.107-debian/*
  except:
    refs:
      - schedules
 
2.4.107 Scheduler:
  extends: .build
  variables:
    FOLDER: "2.4.107-debian"
    VERSION: "2.4.107"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-08
  only:
    refs:
      - schedules 

2.4.107 Manual:
  extends: .build
  variables:
    VERSION: "2.4.107"
    FOLDER: "2.4.107-debian"
    TAGS: "${FOLDER}-dev latest-dev"
    RELEASE_DATE: 2019-08
  when: manual
  except:
    refs:
      - schedules